---
language: python
python: "2.7"

sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

  # Work around that the repo is not called like the role
  - ln -s ansible-role-letsencrypt ../evgeni.letsencrypt

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # TravisCI runs on an older Ubuntu which does not have dehydrated yet
  # don't do this at home!
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/d/dehydrated/dehydrated_0.3.1-3_all.deb && sudo dpkg -i dehydrated_0.3.1-3_all.deb

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --become

  # Run the role/playbook again
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --become | tee -a /tmp/ansible-playbook-test.log

  # make sure it's idempotent.
  - >
    grep -q 'changed=0.*failed=0' /tmp/ansible-playbook-test.log
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
