---
# handlers file for letsencrypt
- name: run letsencrypt.sh
  become: true
  become_user: "{{ letsencrypt_user }}"
  command: letsencrypt.sh --cron --config {{ letsencrypt_basedir }}/config.sh
  when: letsencrypt_domains|length > 0
